import type { Metadata } from "next";
import { cookies } from 'next/headers';

import { Navbar } from "./navbar";

export const metadata: Metadata = {
  title: "Sample Layout",
  description: "Generated by create next app",
};

export default async function SampleLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = await cookies();
  const theme = cookieStore.get('theme')?.value || "light";

  return (
    <>
      <Navbar theme={theme} />
      <div>
        <section>layout pages</section>
        <section>
          {children}
        </section>
      </div>
    </>
  );
}
