version: '3.8'

services:
  pocket-engine:
    build:
      context: ./pocket-engine
      dockerfile: Dockerfile.dev
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./pocket-engine:/app
    ports:
      - "3010:3010"

  pocket-ui:
    build:
      context: ./pocket-ui
      dockerfile: Dockerfile.dev
    volumes:
      - ./pocket-ui:/app
    environment:
      #if you’re not using Windows, you may need comment the next line, set value to true or integer (milliseconds)
      - WATCHPACK_POLLING=1000
      - AUTH_SECRET=WYIB8UBFGJF031XEOQNCF
      - API_URL=http://localhost:3010
    ports:
      - "3000:3000"

  postgres:
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: epocket
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: epocket
    volumes:
      - ./pocket-db/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U epocket -d epocket" ]
      interval: 5s
      timeout: 10s
      retries: 5

  migrate:
    image: migrate/migrate
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./pocket-db/migrations:/migrations
    command: [ "-path", "/migrations", "-database", "postgres://epocket:secret@postgres:5432/epocket?sslmode=disable", "up" ]
