import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "[authenticated]",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <section>
      <section>authenticated layout pages</section>
      <section>
        {children}
      </section>
    </section>
  );
}
