import type { Metadata } from "next";

import ClientSideLayout from './ClientSideLayout';

export const metadata: Metadata = {
  title: "[authenticated]",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClientSideLayout>
      {children}
    </ClientSideLayout>
  );
}
