FROM golang:1.23.4-alpine3.21

# Set the working directory
WORKDIR /app

# Install Air and other dependencies
RUN apk add --no-cache git && \
  go install github.com/air-verse/air@latest

# Install Go dependencies first
COPY go.mod go.sum ./
RUN go mod download

# Copy all source code
COPY . .

# Expose the app's port
EXPOSE 3010

# Start the app with live reload
CMD ["air"]
