FROM golang:1.23.4-alpine3.21

WORKDIR /app

COPY . .

# Download and install the dependencies:
RUN go get -d -v ./...

# Build the go app
RUN go build -o pocket-engine .

EXPOSE 8000

CMD ["./pocket-engine"]